### ISSUE TITLE
Jigsaw puzzle 진행(shanghaitech)

### ISSUE THREAD

**Issue by 2junhyeok** [yugwangyeol/Self-Supervised-Learning-for-Video-Anomaly-Detection#2]
1.
https://svip-lab.github.io/dataset/campus_dataset.html 
OneDrive 다운로드

2.
gpu 서버 data 디렉토리에 upload

3.
sudo apt-get install p7zip-full
7z x -r splits.zip

4.
cat shanghaitech.tar.gz.* > shanghaitech.tar.gz

5.
tar -xvzf shanghaitech.tar.gz

6.
main.py, dataset.py, gen_patches.py 의 data_dir 수정

7.
python main.py --dataset shanghaitech --val_step 100 --print_interval 20 --batch_size 192 --sample_num 9 --epochs 100 --static_threshold 0.2
해당 코드 실행시, 
num_samples가 0이 되는 문제가 발생.

**Comment by yugwangyeol** [comment]
main.py에 경로를 프레임이 들어간 경로를 넣으셨나요? 아님 gen_patch.py로 생성한 결과물 경로를 넣으셨나요?

**Comment by yugwangyeol** [comment]
![image](https://github.com/user-attachments/assets/ca1d28fc-2bd7-45d9-8747-d3492d2649d8)

준혁님 혹시 이 과정 이후에 오류 난 적이 있나요?@2junhyeok

**Comment by 2junhyeok** [comment]
그 과정에서 오류난 적은 없습니다

**Comment by yugwangyeol** [comment]
감사합니다! 그럼 위에서 말씀하신 오류는 저 이미지 과정 이전에서 발생한 오류인가요?

**Comment by 2junhyeok** [comment]
완료했습니다
