### ISSUE TITLE
Data Construction

### ISSUE THREAD

**Issue by yugwangyeol** [yugwangyeol/Self-Supervised-Learning-for-Video-Anomaly-Detection#4]
Data 구축하는 Code 공유해놨습니다!
현재 train version만 공유해놨습니다.
추후 추가 업로드하겠습니다

파일명: copy_images_train.sh (gwang branch)

실행
1. chmod +x copy_images.sh
2. ./copy_images.sh

DAD_C라는 폴더 만들고 시작했습니다.
현재 세팅은 front_IR을 복사하도록 되어있습니다.

**Comment by yugwangyeol** [comment]
제가 알기로는 Jigsaw VAD가 학습할 때 normal만 사용하여 Puzzle 푸는 것을 학습하고, inference/test 과정에서 anomaly 들어왔을 때는 puzzle을 잘 풀지 못하는 걸로 알고 있습니다.
그리고 기존 base에서 사용한 shanghaitech train 데이터도 normal만 사용한 것으로 알고 있습니다.

이러한 이유로 normal_driving만 사용하고 있습니다!
@ryeongseo

**Comment by ryeongseo** [comment]
넵 감사합니다!
저도 코드 업로드 했습니다!

파일명 : restructure_dataset.py (ryeongseo branch)

#### 폴더 구조 변경 사항
##### Train data
1. `Tester1` ~ `Tester25` 폴더를 각각 `01` ~ `25`로 변경
2. 각 행동 폴더는 다음과 같이 라벨링
    - `normal_driving_1` → `001`
    - `normal_driving_2` → `002`
    - `normal_driving_3` → `003`
    - `normal_driving_4` → `004`
    - `normal_driving_5` → `005`
    - `normal_driving_6` → `006`
3. 각 Tester 폴더와 행동 폴더의 번호를 결합하여 새로운 폴더명을 생성
    - `Tester1`의 `normal_driving_1` → `01_001`
4. `frames` 폴더 아래에 `01_001`, `01_002`, …, `25_006` 폴더들이 위치
5. `front_depth`, `front_IR`, `top_depth`, `top_IR` 폴더 아래에  `frames` 폴더가 위치
6. 모든 폴더는 `DAD/training`의 하위 폴더에 위치
##### Test data
1. `val01` ~ `val06` 폴더는 각각 `01` ~ `06`으로 변경
2.  `rec1` ~ `rec6` 폴더는 각각 `0001` ~ `0006`으로 변경
3. 각 val 폴더와 rec 폴더의 번호를 결합하여 새로운 폴더명을 생성
    - `val01`의 `rec1` → `01_0001`
    - `val06`의 `rec6` → `06_0006`
4. `frames` 폴더 아래에 `01_0001`, `01_0002`, …, `06_0006` 폴더들이 위치
5. `front_depth`, `front_IR`, `top_depth`, `top_IR` 폴더 아래에  `frames` 폴더가 위치
6. 모든 폴더는 `DAD/testing`의 하위 폴더에 위치

#### 변경된 폴더 구조
[DAD 폴더 구조.txt](https://github.com/user-attachments/files/17266794/DAD.txt)
          
최대한 코드 변경을 하지 않기 위해..파일명도 변경했습니다!

**Comment by yugwangyeol** [comment]
restructure_dataset.py 하나로 저거 전부 수행 가능한거면 서령님 코드로 다 통일할까요?

**Comment by yugwangyeol** [comment]
val 데이터에 대한 Label 데이터 만드는 generate_frame_masks.py 파일 업로드 해놨습니다! (gwang branch)

해당 파일 사용하시면 DAD 데이터 셋에서 제공한 LABEL.csv 사용해서 Jigsaw-VAD에 필요한 라벨 npy 파일 생성해 줍니다!
경로는 폴더 구조를 서령님과 통일해놔서 그냥 파일 사용하셔도 괜찮을 거 같습니다!
@ryeongseo @2junhyeok

**Comment by yugwangyeol** [comment]
앞으로 남은 일

- [x] gen_patches.py로 train, test 돌리기
- [x] main train/inference 단계에서 object 추출 없애기
- [x] train 진행
- [ ] inference 확인

**Comment by yugwangyeol** [comment]
원 코드를 유지한다는 가정하에 gen_patches.py 파일 돌리려면 기존 파일명처럼 수정해야 할 거 같아서, 이미지 명들 바꾸는 코드 업로드 해놨습니다!.

img_name_change.py (gwang branch)

**Comment by ryeongseo** [comment]
gen_patches.py 에도 객체 처리하는 부분이 있어서 좀 수정했는데 이 파일로 실행해도 괜찮을까요..?

파일명 : gen_patches.py (ryeongseo branch)

#### 수정 사항
- shanghaitech 대신 DAD_jigsaw 넣기
- read_single_frame 함수 frame 형식 변경
- ped2, avenue 데이터셋 관련 코드 삭제
- object detection 관련 코드 제거
- argparse에 data_type(front_depth, front_IR, top_depth, top_IR), data_dir 추가

#### 실행 코드
`python gen_patches.py --phase train --sample_num 9 --data_type top_IR --data_dir /home/work/Alpha/Jigsaw-VAD`

일단 돌아가긴 합니다.. 객체가 아니라 전체 프레임 처리해서 오래 걸리는 걸까요..?
![image](https://github.com/user-attachments/assets/78094247-8aff-4618-a505-9f989c455f89)

@yugwangyeol @2junhyeok

**Comment by yugwangyeol** [comment]
실행해도 괜찮을 거 같습니다! 프레임 단위에다가 shanghaitech 데이터 보다가 양이 많다 보니 오래 걸리는 거 같습니다!
@ryeongseo

**Comment by yugwangyeol** [comment]
기존 원본 코드 유지한 gen_patches.py 업로드했습니다. (gwang branch)

기존 object 대신에 frame을 사용하도록 했습니다.
하단에 main에서 front_IR로 실행하도록 되어있어서, 해당 부분 변경하셔서 진행하시면 될 거 같습니다.

**Comment by yugwangyeol** [comment]
기존 gen_patch_dad.py 파일에서 test시 존재하지 않는 10000.png를 찾는 오류가 있어서 해당 오류 수정한 py파일 업로드 했습니다!

**Comment by ryeongseo** [comment]
기존 gen_patches.py (ryeongseo branch)가 test data 돌리는 과정에서 `ValueError: invalid literal for int() with base 10: 'img_10000.png' ` 오류가 나서 `read_frame_data` 함수 수정해서 업데이트했습니다!

파일명 : gen_patches.py (ryeongseo branch)

train data는 gen_patches.py 돌리는데 7시간 걸렸습니다! 참고하시면 좋을 것 같습니다!
