### ISSUE TITLE
JigsawVAD on DAD

### ISSUE THREAD

**Issue by ryeongseo** [yugwangyeol/Self-Supervised-Learning-for-Video-Anomaly-Detection#7]
어제 수정한 파일 main에 모두 업로드 해놨는데 오늘 train 진행 상황 확인해보니 오류가 났습니다..

![image](https://github.com/user-attachments/assets/8b0d2c16-52aa-41bf-b119-b32efc3b7bae)

dataset.py에서 `read_single_frame` 함수를 gen_patches.py에 있는 `read_single_frame`함수랑 동일하게 수정했습니다!
수정한 파일 main에 다시 업로드했으니까 수정된 버전으로 저장하세요!

**Comment by yugwangyeol** [comment]
감사합니다!

**Comment by yugwangyeol** [comment]
서령님 dataset.py 파일하고 gen_patch.py 파일에서 `read_single_frame` 함수는 똑같은데, dataset.py 파일의 `read_frame_data`함수랑 gen_patches.py에 있는 `read_frame_data` 함수가 다르게 올라와져 있어서 확인 한번 부탁드립니다~

dataset.py에서 `if frame + f < len(frame_list):` 이 부분이 빠져 있는 거 같습니다.
감사합니다!

@ryeongseo

**Comment by ryeongseo** [comment]
`read_frame_data` 함수도 수정해서 dataset.py 다시 올렸습니다!

**Comment by yugwangyeol** [comment]
감사합니다!

**Comment by yugwangyeol** [comment]
![image](https://github.com/user-attachments/assets/69677655-b538-4ea2-aefa-24a8a8997313)

front_IR 학습 되는거 확인했습니다!

**Comment by ryeongseo** [comment]
Train 5 epoch에서 다시 오류났습니다..

![image](https://github.com/user-attachments/assets/7bbc646c-8e67-4b9a-a596-a508ee41c5fd)

@2junhyeok @yugwangyeol

**Comment by yugwangyeol** [comment]
![image](https://github.com/user-attachments/assets/ccde7197-cab3-426f-82cf-f6bec6ba793e)
- 광열 서버

![image](https://github.com/user-attachments/assets/ee6fa49d-6f30-4173-8374-394ed98a61fb)
- 서령 서버

서령님 서버에서 돌린 것과 제 서버에서 돌린 거 모두 score을 계산할 때 Nan 값이 존재하는데, 제가 파악하기로는 Temporal score에서 Nan 값이 발생하는 거 같습니다. 에러가 발생한 시점이 똑같아서 데이터 문제일 수도 있고 아니면 다른 이유일 수도 있을 거 같습니다.

가장 쉬운 방법으로는 nan 값은 0 또는 평균 값으로 바꾸는 방법이 있는데 어떻게 하면 좋을지 의견 주시면 좋을 거 같습니다!
아니면 각자 일단 이 문제를 해결하고 알려주시면 감사하겠습니다!

@ryeongseo @2junhyeok

**Comment by yugwangyeol** [comment]
추가적으로 Jigsaw-VAD 주석 단것과, 기존 shanhaitech 데이터가 3차원이라서 DAD 데이터에 맞게 1차원으로 코드 수정하였습니다. 해당 코드는 제 branch에서 확인하시면 될 거 같습니다!

**Comment by yugwangyeol** [comment]
![image](https://github.com/user-attachments/assets/ef6f96d5-b569-4061-afbb-7f9072d1a774)

evaluate 파일에서 compute_auc, compute_auc_average 함수에서 발생하는 Nan 값을 위 이미지처럼 처리하였습니다!

- distance가 모둔 Nan일 경우 해당 distance를 skip
- 다른 distance가 존재할 경우 Nan값을 제외한 distance의 평균으로 대체

![image](https://github.com/user-attachments/assets/3d7bf3ec-4c91-4a87-b89c-3b4a22c59ca2)

해당 코드 추가 시 다음과 같은 output 출력, 24,25,26,28에 Nan 값 발생 1로 대체

현재 코드 문제없이 돌아가는 걸로 확인 epoch 50으로 돌리는 중 (100은 너무 오래 걸릴 거 같아서)

수정된 eavluate는 gwang branch에 있습니다!

**Comment by yugwangyeol** [comment]
추가적으로 해당 evaluate를 사용하실 분은 print 문에 nan값이 몇개고, 전체 길이가 몇인지 확인하는 코드도 추가되면 좋을거 같습니다!

**Comment by yugwangyeol** [comment]
이거 뒤로 갈수록 Nan 값 개수가 증가해서 시험 끝나고 같이 원인 찾으면 좋을 거 같습니다!
잊어버릴까 봐 이슈 남깁니다.

**Comment by yugwangyeol** [comment]
![image](https://github.com/user-attachments/assets/b998d273-89cc-429d-b511-295781bbce22)

25에폭까지 도달하니까 위와 같은 에러가 발생합니다! 아무래도 원인을 찾아야 할거 같아요!
Nan 값이 발생하는 위치는 temporal에서만 발생하는 것으로 확인됩니다!

**Comment by yugwangyeol** [comment]
![image](https://github.com/user-attachments/assets/0cf86e15-0752-4d0e-8ec1-b475ab23c551)

evlauate 때 사용하는 pkl 파일 보면 temporal 점수가 모두 같은 값을 가지는 것을 확인할 수 있습니다

**Comment by yugwangyeol** [comment]
dataset.py 파일에서 이미지 리스트를 sort 하는 과정에서 문자열로 sort 하는 문제로 인해 오류가 발생하였습니다. 해당 문제 해결 하여 main branch에 올려놨습니다!
